import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
let server,root,content,revision=0;const url='http://127.0.0.1:4191';
before(async()=>{root=await mkdtemp(path.join(tmpdir(),'storm-test-'));await mkdir(root+'/src/data',{recursive:true});await mkdir(root+'/public',{recursive:true});content=JSON.parse(await readFile('src/data/content.json','utf8'));await writeFile(root+'/src/data/content.json',JSON.stringify(content));await writeFile(root+'/public/content.json',JSON.stringify(content));server=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'4191',PORTFOLIO_DATA_ROOT:root},stdio:['ignore','pipe','inherit']});await new Promise((res,rej)=>{server.stdout.once('data',res);server.once('error',rej);server.once('exit',code=>rej(new Error('Test server exited before ready: '+code)))});});
after(()=>server?.kill('SIGTERM'));
async function save(c,r,action='save',origin=url){return fetch(url+'/api/content',{method:'PATCH',headers:{'content-type':'application/json',origin},body:JSON.stringify({content:c,revision:r,action})});}
test('saving a draft preserves published content',async()=>{content.profile.intro='A draft for the editor test';const r=await save(content,revision);assert.equal(r.status,200);revision=(await r.json()).revision;assert.notEqual(JSON.parse(await readFile(root+'/public/content.json','utf8')).profile.intro,content.profile.intro);assert.equal((await(await fetch(url+'/api/content')).json()).content.profile.intro,content.profile.intro)});
test('stale revisions cannot overwrite a newer draft',async()=>{assert.equal((await save(content,0)).status,409)});
test('publishing persists local source and public JSON',async()=>{const r=await save(content,revision,'publish');assert.equal(r.status,200);revision=(await r.json()).revision;assert.equal(JSON.parse(await readFile(root+'/public/content.json','utf8')).profile.intro,content.profile.intro);assert.equal(JSON.parse(await readFile(root+'/src/data/content.json','utf8')).profile.intro,content.profile.intro);const saved=JSON.parse(await readFile(root+'/src/data/content.json','utf8'));assert.equal(saved.ai.hero,content.ai.hero);assert.deepEqual(saved.ai.gallery,content.ai.gallery);assert.deepEqual(saved.projects.map(p=>p.blocks),content.projects.map(p=>p.blocks))});
test('foreign origins cannot save content',async()=>{assert.equal((await save(content,revision,'save','https://example.com')).status,403)});
test('duplicate project routes are rejected',async()=>{const c=structuredClone(content);c.projects[1].slug=c.projects[0].slug;assert.equal((await save(c,revision)).status,400)});
test('uploads verify image bytes and save local assets',async()=>{let form=new FormData();form.append('file',new Blob(['fake image'],{type:'image/png'}),'spoof.png');assert.equal((await fetch(url+'/api/upload',{method:'POST',body:form})).status,400);const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jR6cAAAAASUVORK5CYII=','base64');form=new FormData();form.append('file',new Blob([png],{type:'image/png'}),'pixel.png');const r=await fetch(url+'/api/upload',{method:'POST',body:form});assert.equal(r.status,201);const result=await r.json();assert.ok(result.src.startsWith('/assets/uploads/'));assert.deepEqual(await readFile(path.join(root,'public',result.src)),png)});
