const {spawn}=require('node:child_process'),fs=require('node:fs/promises'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const server=spawn(process.execPath,['server/index.mjs'],{stdio:['ignore','pipe','inherit'],env:{...process.env,PORT:'4190'}});await new Promise((res,rej)=>{server.stdout.once('data',res);server.once('error',rej)});let browser;
try{
 let launch={headless:true};if(process.env.CHROMIUM_PACKAGE){const chrome=require(process.env.CHROMIUM_PACKAGE);launch={...launch,executablePath:process.env.CHROMIUM_EXECUTABLE||await chrome.executablePath(),args:chrome.args.filter(a=>!['--disable-web-security','--allow-running-insecure-content','--disable-site-isolation-trials'].includes(a))};}
 browser=await chromium.launch(launch);const page=await browser.newPage({viewport:{width:1440,height:960}}),base='http://127.0.0.1:4190',errors=[],checks=[];page.on('pageerror',e=>errors.push(String(e)));await fs.mkdir('test-results',{recursive:true});
 await page.goto(base+'/');await page.locator('.morph-card').first().waitFor();await page.evaluate(()=>{const el=document.querySelector('.storm-journey');scrollTo({top:el.offsetHeight-innerHeight,behavior:"instant"})});await page.waitForTimeout(500);
 const boxes=await page.locator('.morph-card').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}}));assert.equal(boxes.length,9);assert.equal(new Set(boxes.map(b=>Math.round(b.x))).size,3);assert.equal(new Set(boxes.map(b=>Math.round(b.y))).size,3);assert.ok(boxes.every(b=>b.x>=0&&b.x+b.w<=1440&&b.y>=200&&b.y+b.h<=925));await page.screenshot({path:'test-results/16-nine-card-grid.png'});checks.push('all nine vortex cards settle into three visible rows without overlap');
 await page.goto(base+'/work/');await page.locator('.project-grid').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/17-work-grid.png'});const hrefs=await page.locator('.project-card').evaluateAll(es=>es.map(e=>e.getAttribute('href')));assert.deepEqual(hrefs.map(h=>h.split('/').pop()),['websites','build-it','spar','ph4ge','illovo','tops-at-spar','individual-projects','art-portfolio','lab']);checks.push('work index follows original website order plus AI');
 await page.goto(base+'/work/build-it/');assert.deepEqual(await page.locator('.project-text-block h2').allTextContents(),['TV Commercial','Promotions','Conventions','Billboards','Digital (I also have fun)']);assert.deepEqual(await page.locator('.ordered-project>section').evaluateAll(es=>es.map(e=>e.dataset.block)),['text','video','text','gallery','text','gallery','gallery','text','gallery','text','gallery','text','video','video']);await page.locator('.project-text-block').first().scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/18-source-order.png'});checks.push('Build it text and film positions match the reference');
 await page.goto(base+'/work/individual-projects/');assert.equal(await page.locator('.ordered-project>section').nth(4).getAttribute('data-block'),'video');await page.goto(base+'/work/illovo/');assert.equal(await page.locator('.ordered-project>section').first().getAttribute('data-block'),'video');checks.push('Individual Projects and Illovo retain original film positions');
 for(const size of [{width:1366,height:768},{width:1280,height:720}]){await page.setViewportSize(size);await page.goto(base+'/about/');await page.locator('.mind-cv img').evaluate(im=>im.decode());assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight),size.height);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),size.width);assert.ok(await page.locator('.mind-interaction').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));}await page.screenshot({path:'test-results/19-mind-laptop.png'});checks.push('Mind page fits common laptop heights');
 await page.setViewportSize({width:640,height:400});await page.goto(base+'/about/');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),640);await page.locator('.mind-cv').scrollIntoViewIfNeeded();await page.locator('.mind-cv a').click();await page.waitForURL('**/cv');checks.push('narrow or zoomed Mind page scrolls accessibly and CV remains clickable');
 await page.goto(base+'/studio/');await page.getByRole('tab',{name:'Projects',exact:true}).click();await page.getByRole('button',{name:/Build it/}).first().click();assert.equal(await page.locator('.editor-block').count(),14);await page.locator('.editor-block').first().locator('summary').click();assert.equal(await page.getByRole('textbox',{name:'Section heading',exact:true}).first().inputValue(),'TV Commercial');await page.getByRole('tab',{name:'CV & pages'}).click();assert.equal(await page.getByText('Show editorial CV',{exact:true}).count(),0);checks.push('Studio exposes ordered text sections and only the original CV');
 assert.deepEqual(errors,[]);await fs.writeFile('test-results/revision.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));
}finally{await browser?.close();server.kill('SIGTERM')}})().catch(e=>{console.error(e);process.exitCode=1});
