const http=require('node:http'),path=require('node:path'),fs=require('node:fs/promises'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const prefix='/CREATIVE-STORM-PORTFOLIO',root=path.resolve('dist');const types={'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.woff2':'font/woff2'};
const server=http.createServer(async(req,res)=>{try{let part=new URL(req.url,'http://localhost').pathname;if(!part.startsWith(prefix+'/')){res.writeHead(404);return res.end()}let file=path.join(root,part.slice(prefix.length));if((await fs.stat(file)).isDirectory()){if(!part.endsWith('/')){res.writeHead(308,{Location:part+'/'});return res.end();}file=path.join(file,'index.html');}const data=await fs.readFile(file);res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end('Not found')}});await new Promise(r=>server.listen(4189,'127.0.0.1',r));let browser;
try{let launch={headless:true};if(process.env.CHROMIUM_PACKAGE){const chrome=require(process.env.CHROMIUM_PACKAGE);launch={...launch,executablePath:process.env.CHROMIUM_EXECUTABLE||await chrome.executablePath(),args:chrome.args.filter(a=>!['--disable-web-security','--allow-running-insecure-content','--disable-site-isolation-trials'].includes(a))};}browser=await chromium.launch(launch);const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));const base='http://127.0.0.1:4189'+prefix;
await page.goto(base+'/');await page.locator('.morph-card').first().waitFor();await page.locator('.atmosphere canvas').waitFor();await page.getByRole('button',{name:'Pause motion',exact:true}).click();await page.locator('.brand-section').scrollIntoViewIfNeeded();await page.waitForTimeout(300);const images=await page.locator('.brand img').evaluateAll(ims=>ims.map(im=>({src:im.getAttribute('src'),loaded:im.complete&&im.naturalWidth>0})));assert.ok(images.every(im=>im.loaded&&im.src.startsWith(prefix+'/assets/')));await page.screenshot({path:'test-results/08-colour-logos.png'});
await page.locator('.navigation').getByRole('link',{name:'Work',exact:true}).click();await page.waitForURL(base+'/work');await page.locator('.project-card[href$="/work/build-it"]').click();await page.waitForURL(base+'/work/build-it');await page.reload();await page.locator('.project-gallery figure').first().waitFor();assert.equal(await page.locator('.project-gallery figure').count(),23);await page.locator('.project-gallery img').first().evaluate(im=>im.decode());
await page.goto(base+'/cv/alternate/');await page.emulateMedia({media:'print'});assert.equal(await page.locator('.atmosphere').evaluate(el=>getComputedStyle(el).display),'none');assert.equal(await page.locator('.cv-heading').evaluate(el=>getComputedStyle(el).display),'none');await page.locator('.original-cv img').evaluate(im=>im.decode());await page.emulateMedia({media:'screen'});
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:['subfolder homepage and WebGL','all brand image assets','project navigation under subfolder','direct project reload and gallery','CV print stylesheet'],errors}));
}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
